runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /src
  static_dir: dist/src
  secure: always

- url: /
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Link: 
      </src/components/hn-app.js>;rel=preload;as=script,
      </src/components/hn-list.js>;rel=preload;as=script,
      </api/news?page=1>;rel=preload;as=fetch

- url: /(new|ask|show|jobs|favorites)
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Link: 
      </src/components/hn-app.js>;rel=preload;as=script,
      </src/components/hn-list.js>;rel=preload;as=script

- url: /item
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Link: 
      </src/components/hn-app.js>;rel=preload;as=script,
      </src/components/hn-item.js>;rel=preload;as=script

- url: /user
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Link: 
      </src/components/hn-app.js>;rel=preload;as=script,
      </src/components/hn-user.js>;rel=preload;as=script

- url: /api/(.*)
  script: server.app
  secure: always

skip_files:
- es/
- lib/
- node_modules/
- src/
